<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CPURacer.Game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPURacer.Native\CPURacer.Native.csproj" />
  </ItemGroup>

</Project>
