<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>CPURacer.Overlay</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPURacer.Capture\CPURacer.Capture.csproj" />
    <ProjectReference Include="..\CPURacer.Game\CPURacer.Game.csproj" />
    <ProjectReference Include="..\CPURacer.Taskmgr\CPURacer.Taskmgr.csproj" />
    <ProjectReference Include="..\CPURacer.Native\CPURacer.Native.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
  </ItemGroup>

</Project>
