<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CPURacer.Capture</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPURacer.Taskmgr\CPURacer.Taskmgr.csproj" />
    <ProjectReference Include="..\CPURacer.Native\CPURacer.Native.csproj" />
  </ItemGroup>

</Project>
